from pptx import Presentation
import os
import json

def create_ppt(slides_json, topic):
    try:
        slides = json.loads(slides_json)
    except json.JSONDecodeError:
        raise ValueError("❌ Failed to parse JSON")

    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    bullet_slide_layout = prs.slide_layouts[1]

    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = topic
    slide.placeholders[1].text = "Generated by Chatbot"

    for item in slides:
        slide = prs.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = item["title"]
        content = slide.placeholders[1]
        content.text = ""
        for line in item["content"].split("\\n"):
            p = content.text_frame.add_paragraph()
            p.text = line
            p.level = 0

    os.makedirs("output", exist_ok=True)
    output_file = f"output/{topic.replace(' ', '_')}.pptx"
    prs.save(output_file)
    return output_file
